#!/usr/bin/env bash

# $1 = command to run
# $2 = total_runs (optional, default 1)
# $3 = thread_count (optional, default 1)
# $4 = make_target (optional)

cmd=$1
if [[ -z "$cmd" ]]; then
    echo "Usage: $0 '<command>' [total_runs] [thread_count] [make_target]" >&2
    exit 1
fi

total_runs=${2:-1}
thread_count=${3:-1}
make_cmd=$4

if [[ -n "$make_cmd" ]]; then
	make fclean > /dev/null
	make "$make_cmd" > /dev/null
	if (( $? != 0 )); then
		echo "Makefile failed" >&2
		exit 1
	fi
	echo "Makefile successful"
fi

export PATH="$(pwd):$(pwd)/build:$PATH"
SECONDS=0

for ((run = 1; run <= total_runs; run++)); do
	printf '[%s s]:\t Run <%d> of <%d>\n' "$SECONDS" "$run" "$total_runs"
	for ((thread = 1; thread <= thread_count; thread++)); do
		bash -c "$cmd" &
	done
	wait
done
printf '[%s s]:\t Done\n' "$SECONDS"
